### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by sainair** [longwatermelon/paint#1]
i tried doing cmake . in the 'paint' directory and get this `cmake .
-- The C compiler identification is GNU 10.2.0
-- The CXX compiler identification is GNU 10.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
JSON_D_LIB
    linked by target "paint" in directory /home/sainair/Desktop/paint
JSON_INCLUDE
   used as include directory in directory /home/sainair/Desktop/paint
   used as include directory in directory /home/sainair/Desktop/paint
   used as include directory in directory /home/sainair/Desktop/paint
JSON_R_LIB
    linked by target "paint" in directory /home/sainair/Desktop/paint
SDL2MAIN_LIB
    linked by target "paint" in directory /home/sainair/Desktop/paint
SDL2_INCLUDE_DIR
   used as include directory in directory /home/sainair/Desktop/paint
   used as include directory in directory /home/sainair/Desktop/paint
   used as include directory in directory /home/sainair/Desktop/paint
SDL2_LIB
    linked by target "paint" in directory /home/sainair/Desktop/paint

-- Configuring incomplete, errors occurred!
See also "/home/sainair/Desktop/paint/CMakeFiles/CMakeOutput.log".
`
And the output log has alot of stuff i dont understand. What do i do (im on linux btw)

**Comment by longwatermelon** [comment]
Im probably doing this wrong, but I usually use cmake with CMAKE_PREFIX_PATH set as a list of directories delimited by semicolons that all my sdks are under, and that's how cmake finds my dependencies. I will list all the dependencies in readme later, just install all of them under the same directory and then set an environment variable CMAKE_PREFIX_PATH to that path.

**Comment by longwatermelon** [comment]
I also feel obligated to comment that i dont know if my code compiles under linux

**Comment by sainair** [comment]
> I also feel obligated to comment that i dont know if my code compiles under linux

ooh okay that's probably it then. Thank you :)
